# Generated by Django 2.1.1 on 2018-10-25 19:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20181023_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='documents/')),
                ('message', models.TextField()),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime(2018, 10, 26, 0, 47, 1, 331876))),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='ID_No',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1)]),
        ),
    ]
