# Generated by Django 2.0.3 on 2018-10-26 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20181026_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 9, 50, 44, 384604)),
        ),
        migrations.AlterField(
            model_name='student',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 9, 50, 44, 385604)),
        ),
    ]
