# Generated by Django 2.0.3 on 2018-10-27 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20181026_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 16, 44, 4, 386815)),
        ),
        migrations.AlterField(
            model_name='student',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 16, 44, 4, 386815)),
        ),
    ]
