# Generated by Django 2.0.3 on 2018-10-27 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20181027_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 17, 8, 26, 489223)),
        ),
        migrations.AlterField(
            model_name='student',
            name='avg_cgpa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_cgpa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='hsc_marks',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='ssc_marks',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 17, 8, 26, 489223)),
        ),
    ]
